repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix']
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.57.1
          - '@typescript-eslint/eslint-plugin@8.43.0'
          - '@typescript-eslint/parser@8.43.0'
          - eslint-config-next@15.5.3
          - eslint-config-prettier@10.1.8

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md|yaml|yml)$
        exclude: package-lock.json