name: Deploy to Production   # 👈 REQUIRED workflow name

on:
  workflow_dispatch:   # 👈 enables manual trigger from GH CLI or Wez

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Vercel (Production)
        run: |
          npx vercel --token=${{ secrets.VERCEL_TOKEN }} \
            --prod \
            --project=${{ secrets.VERCEL_PROJECT_ID }} \
            --org=${{ secrets.VERCEL_ORG_ID }} \
            --confirm --scope=${{ secrets.VERCEL_ORG_ID }}